runners:
  self-hosted-ubuntu-22.04-x86-64:
    cpu: [16, 32, 64]
    ram: [32, 64, 128]
    disk: default
    family: ["c7a", "c7i", "m7a", "m7i"]
    spot: capacity-optimized
    image: ubuntu22-full-x64

  self-hosted-windows-server-2022-x86-64:
    cpu: [16, 32, 64]
    ram: [32, 64, 128]
    disk: default
    family: ["c7a", "c7i", "m7a", "m7i"]
    spot: capacity-optimized
    image: windowscustomimage

images:
  windowscustomimage:
    platform: "windows"
    arch: "x64"
    owner: "227107093234"
    ami: "ami-0108ce4fb0e0704da"
