runners:
  self-hosted-ubuntu22-full-x64:
    cpu: [16, 32, 64]
    ram: [32, 64, 128]
    disk: default
    family: ["c7a", "c7i", "m7a", "m7i"]
    spot: capacity-optimized
    image: ubuntu22-full-x64
