[package]
name = "sp-domain-sudo"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives of pallet domain sudo"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
async-trait = { version = "0.1.83", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false, features = ["derive"] }
sp-api = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }
sp-inherents = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }

[features]
default = ["std"]
std = [
    "async-trait",
    "codec/std",
    "sp-api/std",
    "sp-inherents/std",
]
