[package]
name = "subspace-data-retrieval"
description = "Fetching data from the archived history of the Subspace Distributed Storage Network."
license = "0BSD"
version = "0.1.0"
authors = ["Teor <teor@riseup.net>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
hex.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
subspace-archiving.workspace = true
subspace-core-primitives.workspace = true
subspace-erasure-coding.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }
tracing.workspace = true

[dev-dependencies]

[features]
parallel = [
    "subspace-archiving/parallel",
]
