[package]
name = "staking"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"]}
bincode = {version = "1.0" }
pallet-domains = {path = "../../crates/pallet-domains", features = ["std", "fuzz"]}
ziggy = { version = "1.3.2", default-features = false  }
sp-domains.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
subspace-runtime-primitives = {workspace = true }
domain-runtime-primitives.workspace = true
frame-support.workspace = true
sp-runtime.workspace = true
sp-core.workspace = true

[features]
fuzzing = []

