[package]
name = "subspace-process"
description = "Process scheduling and logging utilities for the Subspace network"
license = "0BSD"
version = "0.0.1"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>", "Teor <teor@riseup.net>"]
edition.workspace = true
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
supports-color.workspace = true
