[package]
name = "pallet-block-fees"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace node pallet for charging and re-distributing domain transaction fees"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false, features = ["derive"] }
domain-runtime-primitives = { version = "0.1.0", path = "../../primitives/runtime", default-features = false }
frame-support = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }
frame-system = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }
scale-info = { version = "2.11.2", default-features = false, features = ["derive"] }
sp-block-fees = { version = "0.1.0", path = "../../primitives/block-fees", default-features = false }
sp-domains = { version = "0.1.0", path = "../../../crates/sp-domains", default-features = false }
sp-runtime = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }
sp-std = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }

[features]
default = ["std"]
std = [
    "codec/std",
    "domain-runtime-primitives/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-block-fees/std",
    "sp-domains/std",
    "sp-runtime/std",
    "sp-std/std",
]
