[package]
name = "sp-block-fees"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives of pallet block-fees"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
async-trait = { version = "0.1.83", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.12", default-features = false, features = ["derive"] }
domain-runtime-primitives = { version = "0.1.0", default-features = false, path = "../runtime" }
sp-inherents = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }
sp-std = { default-features = false, git = "https://github.com/subspace/polkadot-sdk", rev = "949bb3cfb64ab974e4fc49328fb3e81c96bc0fbe" }

[features]
default = ["std"]
std = [
    "async-trait",
    "codec/std",
    "domain-runtime-primitives/std",
    "sp-inherents/std",
    "sp-std/std",
]
