[package]
name = "subspace-erasure-coding"
description = "Polynomial erasure coding implementation used in Subspace Network"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
]

[lib]
# Necessary for CLI options to work on benches
bench = false

[dependencies]
kzg = { git = "https://github.com/grandinetech/rust-kzg", rev = "6c8fcc623df3d7e8c0f30951a49bfea764f90bf4", default-features = false }
rust-kzg-blst = { git = "https://github.com/grandinetech/rust-kzg", rev = "6c8fcc623df3d7e8c0f30951a49bfea764f90bf4", default-features = false }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }
subspace-kzg = { version = "0.1.0", path = "../../shared/subspace-kzg", default-features = false }

[dev-dependencies]
rust-kzg-blst = { git = "https://github.com/grandinetech/rust-kzg", rev = "6c8fcc623df3d7e8c0f30951a49bfea764f90bf4" }
criterion = "0.5.1"
rand = "0.8.5"

[features]
default = ["std", "parallel"]
std = [
    "kzg/std",
    "rust-kzg-blst/std",
    "subspace-core-primitives/std",
    "subspace-kzg/std",
]
parallel = ["rust-kzg-blst/parallel"]

[[bench]]
name = "commitments"
harness = false
