[package]
name = "sc-subspace-sync-common"
version = "0.1.0"
edition = "2021"
authors = [
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
description = "Synchronization algorithms for Autonomys Network"
license = "0BSD"
repository = "https://github.com/autonomys/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
array-bytes = "6.2.3"
futures = "0.3.31"
sc-client-api = { git = "https://github.com/subspace/polkadot-sdk", rev = "0cadd3f11eb252ab37e6fae28cdba721ea5c08de" }
sc-consensus = { git = "https://github.com/subspace/polkadot-sdk", rev = "0cadd3f11eb252ab37e6fae28cdba721ea5c08de" }
sc-network = { git = "https://github.com/subspace/polkadot-sdk", rev = "0cadd3f11eb252ab37e6fae28cdba721ea5c08de" }
sc-network-sync = { git = "https://github.com/subspace/polkadot-sdk", rev = "0cadd3f11eb252ab37e6fae28cdba721ea5c08de" }
sp-blockchain = { git = "https://github.com/subspace/polkadot-sdk", rev = "0cadd3f11eb252ab37e6fae28cdba721ea5c08de" }
sp-runtime = { git = "https://github.com/subspace/polkadot-sdk", rev = "0cadd3f11eb252ab37e6fae28cdba721ea5c08de" }
tracing = "0.1.40"
