# This action enabling building domain genesis storage used in registering new domain runtime, can be triggered manually or by release creation.
#
# Domain genesis storages are built for releases and for manually triggered runs, uploaded to artifacts and assets.
name: Domain genesis storage snapshot build

on:
  workflow_dispatch:
  push:
    tags:
      - 'domain-genesis-storage-snapshot-*'
      - 'domain-genesis-storage-chronos-*'
      - 'domain-genesis-storage-mainnet-*'

jobs:
  domain-genesis-storage:
    runs-on: ${{ fromJson(github.repository_owner == 'autonomys' &&
      '"runs-on=${{ github.run_id }}-${{ github.run_attempt }}/runner=self-hosted-ubuntu-22.04-x86-64/spot=false"' || '"ubuntu-22.04"') }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build node image
        id: build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          file: docker/node.Dockerfile
          pull: true
          push: false

      - name: Generate testnet domain genesis storages
        run: |
          EVM_SPEC_VERSION=$(sed -nr 's/.*spec_version: ([0-9]+),/\1/p' domains/runtime/evm/src/lib.rs)
          AUTO_ID_SPEC_VERSION=$(sed -nr 's/.*spec_version: ([0-9]+),/\1/p' domains/runtime/auto-id/src/lib.rs)
          docker run --rm -u root ${{ steps.build.outputs.digest }} domain build-genesis-storage --runtime-type evm --chain chronos > evm-domain-genesis-storage-chronos-v$EVM_SPEC_VERSION
          docker run --rm -u root ${{ steps.build.outputs.digest }} domain build-genesis-storage --runtime-type evm --chain devnet > evm-domain-genesis-storage-devnet-v$EVM_SPEC_VERSION
          docker run --rm -u root ${{ steps.build.outputs.digest }} domain build-genesis-storage --runtime-type evm --chain mainnet > evm-domain-genesis-storage-mainnet-v$EVM_SPEC_VERSION
          docker run --rm -u root ${{ steps.build.outputs.digest }} domain build-genesis-storage --runtime-type auto-id --chain chronos > auto-id-domain-genesis-storage-chronos-v$AUTO_ID_SPEC_VERSION
          docker run --rm -u root ${{ steps.build.outputs.digest }} domain build-genesis-storage --runtime-type auto-id --chain devnet > auto-id-domain-genesis-storage-devnet-v$AUTO_ID_SPEC_VERSION
          docker run --rm -u root ${{ steps.build.outputs.digest }} domain build-genesis-storage --runtime-type auto-id --chain mainnet > auto-id-domain-genesis-storage-mainnet-v$AUTO_ID_SPEC_VERSION
          echo "EVM_SPEC_VERSION=$EVM_SPEC_VERSION" >> $GITHUB_ENV
          echo "AUTO_ID_SPEC_VERSION=$AUTO_ID_SPEC_VERSION" >> $GITHUB_ENV

      - name: Upload domain genesis storages to artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.1.3
        with:
          name: domain-genesis-storage
          path: |
            evm-domain-genesis-storage-chronos-v${{ env.EVM_SPEC_VERSION }}
            evm-domain-genesis-storage-devnet-v${{ env.EVM_SPEC_VERSION }}
            evm-domain-genesis-storage-mainnet-v${{ env.EVM_SPEC_VERSION }}
            auto-id-domain-genesis-storage-chronos-v${{ env.AUTO_ID_SPEC_VERSION }}
            auto-id-domain-genesis-storage-devnet-v${{ env.AUTO_ID_SPEC_VERSION }}
            auto-id-domain-genesis-storage-mainnet-v${{ env.AUTO_ID_SPEC_VERSION }}
          if-no-files-found: error

      - name: Upload domain genesis storages to assets
        uses: alexellis/upload-assets@13926a61cdb2cb35f5fdef1c06b8b591523236d3 # 0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["evm-domain-genesis-storage-mainnet-v${{ env.EVM_SPEC_VERSION }}", "evm-domain-genesis-storage-chronos-v${{ env.EVM_SPEC_VERSION }}", "evm-domain-genesis-storage-devnet-v${{ env.EVM_SPEC_VERSION }}", "auto-id-domain-genesis-storage-mainnet-v${{ env.AUTO_ID_SPEC_VERSION }}", "auto-id-domain-genesis-storage-chronos-v${{ env.AUTO_ID_SPEC_VERSION }}", "auto-id-domain-genesis-storage-devnet-v${{ env.AUTO_ID_SPEC_VERSION }}"]'
        # Only run for releases
        if: github.event_name == 'push' && github.ref_type == 'tag'
